// JS CHAPTER 4

// QUESTION 1
// var me = "Humza" , you = "Bilal" , he = "Ashar";
// console.log(me,he,you);
// IS MAI 3 VARIABLE IK SATH DECLARE HUE WAI HAI YANI HUM IK STATMENT MAI MULTIPLE VARIABLES DECLARE KAR SKTAI HAI 